# Generated by Django 5.2.8 on 2026-02-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cart', to='ventas_app.cart')),
            ],
        ),
    ]
