# Generated by Django 5.2.8 on 2026-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_alter_userprofile_dni_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_document',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT/CUIL'), ('PAS', 'PASAPORTE')], default='DNI', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
