# Generated by Django 5.2.8 on 2026-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0004_userprofile_type_document_alter_userprofile_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dni',
            new_name='document',
        ),
    ]
