# Generated by Django 5.2.8 on 2026-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0005_rename_dni_userprofile_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('SOLTERO', 'SOLTERO/A'), ('CASADO', 'CASADO/A'), ('VIUDO', 'VIUDO/A')], default='SOLTERO/A', max_length=10),
        ),
    ]
