# Generated by Django 6.0.2 on 2026-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0008_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name_product',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
