# Generated by Django 6.0.2 on 2026-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0009_alter_products_name_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
