# Generated by Django 6.0.2 on 2026-02-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0011_alter_products_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
