# Generated by Django 6.0.2 on 2026-02-20 22:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0012_alter_products_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_product',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
