# Generated by Django 6.0.2 on 2026-02-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0017_invoice_detailpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='user_addres',
            new_name='user_address',
        ),
    ]
