# Generated by Django 6.0.2 on 2026-02-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0018_rename_user_addres_invoice_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
