# Generated by Django 6.0.2 on 2026-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0020_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpurchase',
            name='name_product',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
